FROM golang:alpine
ENV CGO_ENABLED=0

WORKDIR /app
COPY . .

COPY go.mod go.sum ./
RUN go mod download


# Skaffold passes in debug-oriented compiler flags
ARG SKAFFOLD_GO_GCFLAGS
RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o main .

CMD ["./main"]